springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  paths-to-match: /**
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
server:
  servlet:
    context-path: /v1
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    data: classpath:data.sql
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:qualitydb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      format_sql: true
    defer-datasource-initialization: true
  mvc:
    throw-exception-if-no-handler-found: true # Whether a "NoHandlerFoundException" should be thrown if no Handler was found to process a request.
  web:
    resources:
      add-mappings: false
